---
title: "Florida Keys Reef Fish Biodiversity"
author: "Megan Hepner"
date: '2017-05-05'
categories: []
tags: []
---

Based on @mhepner90 's work to load and analyze RVC data.
Original version can be found [here](https://github.com/mhepner90/RVC/blob/master/SDG14/MBON_SDG14_FKNMS_classification.Rmd).

## Sustainable Development Goal

SDG14: Conserve and sustainably use the oceans, seas and marine resources
    + SDG14.2:VBy 2020, sustainably manage, and protect marine and coastal ecosystems to avoid significant adverse impacts, including by strengthening their resilience and take action for their restoration, to achieve healthy and productive oceans

## National Marine Sanctuary Condition Report Questions

### Water Quality
1. What is the eutrophic condition of the sanctuary waters and how is it changing?
2. Do sanctuary waters pose risks to human health and how are they changing?
3. Have recent changes in climate alter water conditions and how are they changing?
4. Are other stressors, individually or in combination, affecting water quality, and how are they changing?

### Habitat Resources
5. What is the integrity of major habitat types and how are they changing?
6. What are contaminant concentrations in sanctuary habitats and how are they changing?

### Living Resources
7. What is the status and trend of keystone and foundation species and how is it changing?
8. What is the status and trend of other focal species and how is it changing?
9. What is the status of non-indigenous species and how is it changing?
10. What is the status of biodiversity and how is it changing?

### Maritime Archeological Resources  
11. What is the archaeological integrity of known maritime archaeological resources and how is it changing?
12. Do known maritime archaeological resources pose an environmental hazard and how is this threat changing?

### Human Demensions
13. What are the levels of human activities that may adversely influence water quality and how are they changing?
14. What are the levels of human activities that may adversely influence habitats and how are they changing?
15. What are the levels of human activities that may adversely influence living resource quality and how are they changing?
16. What are the levels of human activities that may adversely influence maritime archaeological resource quality and how are they changing?
17. What are the states of influential human drivers and how are they changing?

## FKNMS Infographic data

| Classification level           | Icon                   | Metric                                        | Dataset |
|:-------------------------------|:-----------------------|:----------------------------------------------|:--------|
| Trophic groups                 | Forage fish            | biomass, density                              | RVC     |
| Trophic groups                 | Grouper                | biomass, density, richness simpson, shannon   | RVC     |
| Trophic groups                 | Grunt                  | biomass, density, richness simpson, shannon   | RVC     |
| Trophic groups                 | Higher level reef fish | biomass, density, richness simpson, shannon   | RVC     |
| Trophic groups                 | Hogfish                | biomass, density                              | RVC     |
| Trophic groups                 | Lionfish               | biomass, density                              | RVC     |
| Trophic groups                 | Opportunists           | biomass, density, richness simpson, shannon   | RVC     |
| Trophic groups                 | Parrotfish             | biomass, density, richness simpson, shannon   | RVC     |
| Trophic groups                 | Rays                   | biomass, density                              | RVC     |
| Trophic groups                 | Seabass and Hamlets    | biomass, density, richness simpson, shannon   | RVC     |
| Trophic groups                 | Sharks                 | biomass, density                              | RVC     |
| Trophic groups                 | Small reeffish         | biomass, density, richness simpson, shannon   | RVC     |
| Trophic groups                 | Snapper                | biomass, density, richness simpson, shannon   | RVC     |
| Trophic level                  | Trophic pyramid        | biomass                                       | RVC     |
| Focal species                  | Exploited fish icon    | biomass, density                              | RVC     |
| Biodiversity                   | Reef fish biodiversity | richness, simpson, shannon                    | RVC     |
| Foundation species             | Stony coral            | percent cover & diseased                      | CREMP   |
| Foundation species             | Sea fan                | percent cover & diseased                      | CREMP   |
| Foundation species             | Macroalgae             | percent cover & diseased                      | CREMP   |       
| Foundation species             | Sponges                | percent cover & diseased                      | CREMP   |       
| Keystone species               | Long-spined sea urchin | abundance                                     | TBD     |
| Focal species                  | Caribbean spiny lobster| abundance                                     | TBD     |
| Focal species                  | Queen Conch            | abundance                                     | TBD     |
| Focal species                  | Sea turtles            | abundance                                     | TBD     |


# Reef Visual Census (RVC)
As of 2019-06-06 the RVC server is unavailable (`Error in getTaxonomicData(server) : could not access server`),
so this chunk does not work.

```{r call RVC data, eval=FALSE}
library(knitr)
library(tidyverse)
library(rvc)
library(vegan)
library(dygraphs)
library(grDevices)
library(RColorBrewer)

#rds files to read
RVCdata_FK_rds = 'RVCdata_FK.rds'

#rvc94_16_csv = 'big_csv/rvc94_16.csv'

if (!all(file.exists(RVCdata_FK_rds))){
    #rm(list = ls())
    RVCdata_FK <- getRvcData(
        1999:2016,
        "FLA KEYS",
        server = 'https://www.sefsc.noaa.gov/rvc_analysis20/'
    )
    write_rds(RVCdata_FK, 'RVCdata_FK.rds')

} else{  # read extant data
    RVCdata_FK = read_rds('RVCdata_FK.rds')
}

# add 1994 - 1998 RVC data and reweight by strata
# if (!file.exists(rvc94_16_csv)){
#   rvc98 <-read.csv("90srvc/fk1998_dat2.csv")
#   rvc97 <-read.csv("90srvc/fk1997_dat2.csv")
#   rvc96 <-read.csv("90srvc/fk1996_dat2.csv")
#   rvc95 <-read.csv("90srvc/fk1995_dat2.csv")
#   rvc94 <-read.csv("90srvc/fk1994_dat2.csv")
#   rvc94_16 <- rbind(RVCdata_FK$sample_data, rvc98, rvc97, rvc96, rvc95, rvc94)
#   write_csv(rvc94_16, "big_csv/rvc94_16.csv")
# } else {
#   rvc94_16 = read.csv("big_csv/rvc94_16.csv")
# }
#
# strat94 <- read.csv("90srvc/FKeys_NTOTS_Reweight_1994.csv")
# strat <- strat94[which(strat94$YEAR<1999),]
# RVCdata_FK$sample_data <- rvc94_16
# RVCdata_FK$stratum_data <- rbind(strat,RVCdata_FK$stratum_data)
```
