# based on https://bookdown.org/yihui/blogdown/travis-github.html
language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  # `packages: yes` caches $HOME/R/Library & sets R_LIB_USER=$HOME/R/Library environment variable
  packages: yes
  directories:
    - $HOME/bin
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/src
    - $TRAVIS_BUILD_DIR/static
    - $HOME/.cache/robis_query_cache

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


before_install:
  - sudo apt-get install -y r-cran-ncdf4 libudunits2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev python3 python3-pip

install:
  # - travis_wait 40 ./install_R_deps.sh
  - ./install_python_deps.sh

script:
  - Rscript -e 'blogdown::install_hugo()'
  # TODO: add custom infographiq build step here
  - Rscript -e 'blogdown::build_site()'

# after_success:
# - Rscript -e 'covr::codecov()'

# after_failure:
#   - travis cache --delete

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  # fqdn: travis-blogdown.yihui.name  # this sets CNAME for custom DN
