baseurl = "https://marinebon.github.io/fk-iea/"
languageCode = "en-us"
title = "FKNMS MBON and IEA Webinized Infographic"
theme = "book"
relativeURLs = false
enableEmoji = true
publishDir = "public"  # TODO: change to docs?

ignoreFiles = [
    # ignore .Rmd files bc blogdown compiles them to .html,
    # and it suffices for Hugo to use the .html files.
    # There is no need for Hugo to build .Rmd files,
    # and actually Hugo does not know how.
    "\\.Rmd$", "\\.Rmarkdown$",

    # Directories with suffixes _files and _cache should be ignored bc
    # they contain auxiliary files after an Rmd file is compiled,
    # and blogdown will store them.
    # Hugo should not copy them again to the public/ directory.
    "_files$", "_cache$",

    # rds data files do not need to be copied and attempting to do so
    # may cause hugo to throw errors.
    "\\.rds$"
]

# =========================================================================
# === "book" [theme settings](https://themes.gohugo.io/hugo-book/)
# =========================================================================
# # (Warnings) Theme is intended for documentation use,
# therefore it doesn't render taxonomy.
# # You can hide related warning with config below
# disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
# (Optional, default true) Show or hide table of contents globally
# You can also specify this parameter per page in front matter
BookShowToC = true

# (Optional, default none) Set leaf bundle to render as side menu
# When not specified file structure and weights will be used
BookMenuBundle = "/menu"

# (Optional, default docs) Specify section of content to render as menu
# You can also set value to "*" to render all sections to menu
# BookSection = "docs"

# (Optional) This value is duplicate of $link-color for making active link highlight in menu bundle mode
# BookMenuBundleActiveLinkColor = \#004ed0

# (Optional, default false) Include JS scripts in pages. Disabled by default.
# - Keep side menu on same scroll position during navigation
BookEnableJS = true

# Set source repository location.
# Used for 'Last Modified' and 'Edit this page' links.
BookRepo = "https://github.com/marinebon/fk-iea"

# Enable "Edit this page" links for 'doc' page type.
# Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
# Path must point to 'content' directory of repo.
# BookEditPath = "edit/master/exampleSite/content"

# (Optional, default January 2, 2006) Configure the date format used on the pages
# - In git information
# - In blog posts
BookDateFormat = "2006-01-02"
