```{r mpa compare imports}
library(glue)
# also uses robis
```

```{r mpa areas}
fknms <- "(-83.15 25.65, -80.066667 25.65, -80.066667 24.3, -83.15 24.3, -83.15 25.65)"

# special use areas manually transcribed from images at
# https://floridakeys.noaa.gov/zones/special/welcome.html
# converted from min/degrees to decimal degrees using
# https://www.pgc.umn.edu/apps/convert/

# https://floridakeys.noaa.gov/zones/special/easternsambo.html
eastern_sambo <- "(-81.667167 24.496167, -81.659833 24.497333, -81.655833 24.4925, -81.666 24.4895, -81.667167 24.496167)"


# TODO: include others
# https://floridakeys.noaa.gov/zones/emas/looekey.html
# https://floridakeys.noaa.gov/zones/special/tennessee.html
# https://floridakeys.noaa.gov/zones/special/conchreef.html

# TODO add others here too
inside_mpas <- glue("MULTIPOLYGON (({eastern_sambo}))")
outside_mpas <- glue("MULTIPOLYGON (({fknms},{eastern_sambo}))")
```

```{r fetch mpa compare data}
species_name <- "Ocyurus chrysurus"
inside_occurrence <- robis::occurrence(
    species_name,
    geometry = inside_mpas
)
outside_occurrence <- robis::occurrence(
    species_name,
    geometry = outside_mpas

)
```

```{r mpa compare timeseries}
# TODO: how to make this one plot?
ggplot2::ggplot(inside_occurrence) + ggplot2::geom_bar(ggplot2::aes(date_year), width = 1)
ggplot2::ggplot(outside_occurrence) + ggplot2::geom_bar(ggplot2::aes(date_year), width = 1)
```
