```{r libs, include=FALSE}
library(readr)
library(cowplot)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(tidyverse)
source("read_rds_remote.R")
```

```{r psu biomass}

psu_bio = read_rds_remote(
    "https://raw.github.com/mhepner90/RVC/master/psu_bio_sum_rds",
    "psu_bio.rds"
)
```

```{r psu biodiversity}
psu_div = read_rds_remote(
    "https://raw.github.com/mhepner90/RVC/master/psu_div_rds",
    "psu_div.rds"
)
```

```{r biodiversity 2.0}
fd_evenness = read_rds_remote(
    "https://raw.github.com/mhepner90/RVC/master/fd_eveness_rds",
    "fd_evenness.rds"
)
```

## Plots

- create multiplot function from (https://stackoverflow.com/questions/24387376/r-weird-error-could-not-find-function-multiplot)

 Questions

- Are diversity values and strata related?
- Are diversity values and subregions related?
- Are diversity values and protection level related?

```{r Plot by 7 strata and year in 1 line graph}
all_matrices_data = read_rds_remote(
    "https://raw.github.com/mhepner90/RVC/master/psu_matrices_data_rds",
    "all_matrices_data.rds"
)

stats_all_matrices_data = read_rds_remote(
    "https://raw.github.com/mhepner90/RVC/master/stats_all_matrices_data_rds",
    "stats_all_matrices_data.rds"
)

mean_indices = stats_all_matrices_data %>%
  select(YEAR, STRAT, abundance_mean, biomass_mean, evenness_mean, richness_mean, simpson_mean, shannon_mean, func.div_mean) %>%
  group_by(YEAR, STRAT) %>%
  arrange(YEAR, desc(abundance_mean))

# plot mean and se across strat and year using line graphs

# BY STRAT and YEAR
#abundance
ab_ys = ggplot(stats_all_matrices_data,aes(x=YEAR,y=abundance_mean, colour=STRAT, group=STRAT))+ #shape=STRAT
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymax=abundance_mean+abundance_se,ymin=abundance_mean-abundance_se),width=0.1)+
  labs(title= "A) Abundance", x="Year", y="Mean abundance", colour = "Strata")+
  scale_y_continuous(limits = c(0, 1600), breaks = c(100,200,300,400,500,600,700,800,900,1000,1100,1200, 1300, 1400, 1500, 1600), labels = c("","200","","400","","600","","800","","1000","","1200","","1400","","1600")) +
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
      legend.position="none", #"none", "right",c(0.8,0.68),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.title.x=element_text(size=12),
      axis.title.y=element_text(size=12),
      title=element_text(size=12))
#y=expression(paste("Mean abundance (ind/40,000 km"^"2)")) #in case we need to use superscript in axis label, here is code. it was hard to figure out so I'm leaving it here
#ggsave(file="abundance_by_year_and_strata.pdf", path="big_csv/plots")
print(ab_ys)

#biomass
bio_ys = ggplot(stats_all_matrices_data,aes(x=YEAR,y=biomass_mean, colour=STRAT, group=STRAT))+ #shape=STRAT
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=biomass_mean-biomass_se, ymax=biomass_mean+biomass_se), width=.2) +
  labs(title= "B) Biomass", x="Year", y="Mean biomass", colour = "Strata")+
  scale_y_continuous(limits = c(0, 80), breaks = c(0, 10, 20, 30, 40, 50, 60,70, 80), labels= c("0", "", "20", "", "40", "", "60", "", "80"))+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
      legend.position="none",
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.title.x=element_text(size=12),
      axis.title.y=element_text(size=12),
      title=element_text(size=12))
#ggsave(file="biomass_by_year_and_strata.pdf", path="big_csv/plots")
print(bio_ys)

# evenness
eve_ys = ggplot(stats_all_matrices_data,aes(x=YEAR,y=evenness_mean, colour=STRAT, group=STRAT))+ #shape=STRAT
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymax=evenness_mean+evenness_se,ymin=evenness_mean-evenness_se),width=0.1)+
  labs(title= "C) Evenness", x="Year", y="Mean relative evenness",colour = "Strata")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
      legend.position="none", #right
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.title.x=element_text(size=12),
      axis.title.y=element_text(size=12),
      title=element_text(size=12))
#ggsave(file="evenness_by_year_and_strata.pdf", path="big_csv/plots")
print(eve_ys)

#richness
rich_ys = ggplot(stats_all_matrices_data,aes(x=YEAR,y=richness_mean, colour=STRAT, group=STRAT))+ #shape=STRAT
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=richness_mean-richness_se, ymax=richness_mean+richness_se), width=.2)+
  labs(title= "D) Richness", x="Year", y="Mean ENS", colour = "Strata")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  #theme_bw()+
  theme(
      legend.position="none",
      panel.background=element_rect(fill="grey30"),
      panel.grid.major=element_line("grey40"), #element_blank(),
      panel.grid.minor=element_blank(),
      axis.title.x=element_text(size=12),
      axis.title.y=element_text(size=12),
      title=element_text(size=12),
      plot.title =element_text(hjust = 0))
#ggsave(file="richness_by_year_and_strata.pdf", path="big_csv/plots")
print(rich_ys)

#simpson
sim_ys = ggplot(stats_all_matrices_data,aes(x=YEAR,y=simpson_mean, colour=STRAT, group=STRAT))+ #shape=STRAT
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymin=simpson_mean-simpson_se, ymax=simpson_mean+simpson_se), width=.2)+
  labs(title= "E) Simpson", x="Year", y="Mean ENS", colour = "Strata")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
      legend.position="none",
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.title.x=element_text(size=12),
      axis.title.y=element_text(size=12),
      title=element_text(size=12))
#ggsave(file="simpson_diversity_by_year_and_strata.pdf", path="big_csv/plots")
print(sim_ys)

# shannon
shan_ys = ggplot(stats_all_matrices_data,aes(x=YEAR,y=shannon_mean, colour=STRAT, group=STRAT))+ #shape=STRAT
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymax=shannon_mean+shannon_se,ymin=shannon_mean-shannon_se),width=0.1)+
  labs(title= "F) Shannon", x="Year", y="Mean ENS", colour = "Strata")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
      legend.position="none",
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.title.x=element_text(size=12),
      axis.title.y=element_text(size=12),
      title=element_text(size=12))
#ggsave(file="shannon_diversity_by_year_and_strata.pdf", path="big_csv/plots")
print(shan_ys)

# functional
func_ys= ggplot(stats_all_matrices_data,aes(x=YEAR,y=func.div_mean, colour=STRAT, group=STRAT))+ #shape=STRAT
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  geom_errorbar(aes(ymax=func.div_mean+func.div_se,ymin=func.div_mean-func.div_se),width=0.1)+
  labs(title= "G) Functional", x="Year", y="Mean ENS", colour = "Strata")+
  scale_x_continuous(limits = c(1999, 2016), breaks = c(2000,2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016), labels=c("2000","","2004","","2008","","2012","","2016"))+
  theme_bw()+
  theme(
      legend.position="none",
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      axis.title.x=element_text(size=12),
      axis.title.y=element_text(size=12),
      title=element_text(size=12))
#ggsave(file="functional_diversity_by_year_and_strata.pdf", path="big_csv/plots")
print(func_ys)

#save legend
for_legend_vert = ggplot(stats_all_matrices_data,aes(x=YEAR,y=abundance_mean, colour=STRAT, group=STRAT))+
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  labs(colour = "Strata")+
  theme(
      legend.position="right", #"none", "right",c(0.8,0.68),
      legend.text=element_text(size=11),
      legend.key.size=unit(5,"mm"))
legend_vert <- get_legend(for_legend_vert)

for_legend_horiz = ggplot(stats_all_matrices_data,aes(x=YEAR,y=abundance_mean, colour=STRAT, group=STRAT))+
  geom_line(aes(group=STRAT),lwd=1) +
  geom_point(size=3) +
  labs(colour = "Strata")+
  theme(
      legend.position="bottom", #"none", "right",c(0.8,0.68),
      legend.text=element_text(size=11),
      legend.key.size=unit(5,"mm"))
legend_horiz <- get_legend(for_legend_horiz)

#combine multiple plots
#all plots on one page
g_ys <- grid.arrange(ab_ys,bio_ys,eve_ys,rich_ys,sim_ys,shan_ys,func_ys,legend_vert,ncol=2)
#ggsave(file="all_indices_by_year_and_strata.pdf", g_ys, width=7, height=10, path="big_csv/plots")
print(g_ys)

#plots on two pages - letters in plot titles will need to be changed so they make sense on two pages (i.e., A-C and A-D)
g1 <- grid.arrange(ab_ys,bio_ys,eve_ys,legend_vert,ncol=2)
#ggsave(file="ab_bio_eve_by_year_and_strata.pdf", g1, width=7, height=5, path="big_csv/plots")
print(g1)

g2 <- grid.arrange(arrangeGrob(rich_ys,sim_ys,ncol=2),arrangeGrob(shan_ys,func_ys,ncol=2),legend_horiz,nrow=3,heights=c(2,2,.4))
#ggsave(file="rich_shan_sim_func_by_year_and_strata.pdf", g2, width=7, height=6, path="big_csv/plots")
print(g2)

#left=textGrob("Mean number of effective species", gp=gpar(fontsize=12), rot=90), bottom=textGrob("Year",gp=gpar(fontsize=12))) #code to insert global x and y axis labels

### ***Don't need to combine plots by STRAT and by YEAR just YEAR & STRAT for now***

# plot mean and se by years across strat and by strat across years using bar graphs

# by STRAT
#abundance
abun = ggplot(stats_all_matrices_data, aes(x=STRAT, y=abundance_mean)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=abundance_mean-abundance_se, ymax=abundance_mean+abundance_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~YEAR, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(abun)

#biomass
biom = ggplot(stats_all_matrices_data, aes(x=STRAT, y=biomass_mean)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=biomass_mean-biomass_se, ymax=biomass_mean+biomass_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~YEAR, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(biom)

#richness
rich = ggplot(stats_all_matrices_data, aes(x=STRAT, y=richness_mean)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=richness_mean-richness_se, ymax=richness_mean+richness_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~YEAR, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(rich)

#simpson
simp = ggplot(stats_all_matrices_data, aes(x=STRAT, y=simpson_mean)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=simpson_mean-simpson_se, ymax=simpson_mean+simpson_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~YEAR, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(simp)

#shannon
shan = ggplot(stats_all_matrices_data, aes(x=STRAT, y=shannon_mean)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=shannon_mean-shannon_se, ymax=shannon_mean+shannon_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~YEAR, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(shan)

# functional
func = ggplot(stats_all_matrices_data,aes(x=STRAT,y=func.div_mean))+
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=func.div_mean-func.div_se, ymax=func.div_mean+func.div_se), width=.2,  position=position_dodge(.9))+
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~YEAR, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(func)

# evenness
even = ggplot(stats_all_matrices_data,aes(x=STRAT,y=evenness_mean))+
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=evenness_mean-evenness_se, ymax=evenness_mean+evenness_se), width=.2,  position=position_dodge(.9))+
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~YEAR, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(even)

# by YEAR
#abundance
abun = ggplot(stats_all_matrices_data, aes(x=YEAR, y=abundance_mean, group=YEAR)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=abundance_mean-abundance_se, ymax=abundance_mean+abundance_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~STRAT, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(abun)

#biomass
biom = ggplot(stats_all_matrices_data, aes(x=YEAR, y=biomass_mean, group=YEAR)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=biomass_mean-biomass_se, ymax=biomass_mean+biomass_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~STRAT, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(biom)

#richness
rich = ggplot(stats_all_matrices_data, aes(x=YEAR, y=richness_mean, group=YEAR)) +  
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=richness_mean-richness_se, ymax=richness_mean+richness_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~STRAT, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(biom)

#simpson
simp = ggplot(stats_all_matrices_data, aes(x=YEAR, y=simpson_mean, group=YEAR)) +  
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=simpson_mean-simpson_se, ymax=simpson_mean+simpson_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~STRAT, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(simp)

#shannon
shan = ggplot(stats_all_matrices_data, aes(x=YEAR, y=shannon_mean, group=YEAR)) +  
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=shannon_mean-shannon_se, ymax=shannon_mean+shannon_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~STRAT, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(shan)

#functional
func = ggplot(stats_all_matrices_data, aes(x=YEAR, y=func.div_mean, group=YEAR)) +  
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=func.div_mean-func.div_se, ymax=func.div_mean+func.div_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~STRAT, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(func)

#evenness
even = ggplot(stats_all_matrices_data, aes(x=YEAR, y=evenness_mean, group=YEAR)) +  
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=evenness_mean-evenness_se, ymax=evenness_mean+evenness_se), width=.2, position=position_dodge(.9)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90)) +
  facet_wrap(~STRAT, scales='free_y')
#ggsave(file=".pdf", path="big_csv/plots")
print(even)
```
